describe('Formulario 3 - Testes completos', () => {

beforeEach(() => {
    cy.visit('https://carlosfelixpenha-create.github.io/QAPlayground/frontend/pages/formulario-1.html')
})

it('Validar sucesso ao salvar endereço com todos os campos válidos', () => {
    cy.get('#logradouro').type('Rua Rosa Lima')
    cy.get('#numero').type('500')
    cy.get('#complemento').type('Casa')
    cy.get('#bairro').type('Jardim 2')
    cy.get('#cidade').type('Manaus')
    cy.get('#estado').type('Amazonas')
    cy.get('#cep').type('58051425')
    cy.contains('Salvar').click()
    cy.contains('Endereço cadastrado com sucesso!').should('be.visible')
})

it('Validar preenchimento obrigatório do campo Logradouro', () => {
    cy.get('#numero').type('500')
    cy.get('#complemento').type('Casa')
    cy.get('#bairro').type('Jardim 2')
    cy.get('#cidade').type('Manaus')
    cy.get('#estado').type('Amazonas')
    cy.get('#cep').type('58051425')
    cy.contains('Salvar').click()
    cy.contains('Preencher corretamente o campo Logradouro, dúvida entrar em requisitos!').should('be.visible')
})

it('Validar rejeição de Logradouro contendo apenas números', () => {
    cy.get('#logradouro').type('123456789')
    cy.get('#numero').type('500')
    cy.get('#complemento').type('Casa')
    cy.get('#bairro').type('Jardim 2')
    cy.get('#cidade').type('Manaus')
    cy.get('#estado').type('Amazonas')
    cy.get('#cep').type('58051425')
    cy.contains('Salvar').click()
    cy.contains('Preencher corretamente o campo Logradouro, dúvida entrar em requisitos!').should('be.visible')
})

it('Validar preenchimento obrigatório do campo Número', () => {
    cy.get('#logradouro').type('Rua Rosa Lima')
        cy.get('#complemento').type('Casa')
    cy.get('#bairro').type('Jardim 2')
    cy.get('#cidade').type('Manaus')
    cy.get('#estado').type('Amazonas')
    cy.get('#cep').type('58051425')
    cy.contains('Salvar').click()
    cy.contains('Preencher corretamente o campo Número, dúvida entrar em requisitos!').should('be.visible')
})
it('Validar aceitação apenas de números no campo Número', () => {
    cy.get('#logradouro').type('Rua Rosa Lima')
    cy.get('#numero').type('qwdqwcqwf')
    cy.get('#complemento').type('Casa')
    cy.get('#bairro').type('Jardim 2')
    cy.get('#cidade').type('Manaus')
    cy.get('#estado').type('Amazonas')
    cy.get('#cep').type('58051425')
    cy.contains('Salvar').click()
    cy.contains('Preencher corretamente o campo Número, dúvida entrar em requisitos!').should('be.visible')
})

it('Validar que o campo Complemento pode ficar vazio', () => {
    cy.get('#logradouro').type('Rua Rosa Lima')
    cy.get('#numero').type('500')
    cy.get('#bairro').type('Jardim 2')
    cy.get('#cidade').type('Manaus')
    cy.get('#estado').type('Amazonas')
    cy.get('#cep').type('58051425')
    cy.contains('Salvar').click()
    cy.contains('Endereço cadastrado com sucesso!').should('be.visible')
})

it('Validar preenchimento obrigatório do campo Bairro', () => {
    cy.get('#logradouro').type('Rua Rosa Lima')
    cy.get('#numero').type('500')
    cy.get('#complemento').type('Casa')
    cy.get('#cidade').type('Manaus')
    cy.get('#estado').type('Amazonas')
    cy.get('#cep').type('58051425')
    cy.contains('Salvar').click()
    cy.contains('Preencher corretamente o campo Bairro, dúvida entrar em requisitos!').should('be.visible')
})

it('Validar quantidade mínima de caracteres no campo Bairro', () => {
    cy.get('#logradouro').type('Rua Rosa Lima')
    cy.get('#numero').type('500')
    cy.get('#complemento').type('Casa')
    cy.get('#bairro').type('Ja')
    cy.get('#cidade').type('Manaus')
    cy.get('#estado').type('Amazonas')
    cy.get('#cep').type('58051425')
    cy.contains('Salvar').click()
    cy.contains('Preencher corretamente o campo Bairro, dúvida entrar em requisitos!').should('be.visible')
})

it('Validar rejeição de números isolados no campo Bairro', () => {
    cy.get('#logradouro').type('Rua Rosa Lima')
    cy.get('#numero').type('500')
    cy.get('#complemento').type('Casa')
    cy.get('#bairro').type('12')
    cy.get('#cidade').type('Manaus')
    cy.get('#estado').type('Amazonas')
    cy.get('#cep').type('58051425')
    cy.contains('Salvar').click()
    cy.contains('Preencher corretamente o campo Bairro, dúvida entrar em requisitos!').should('be.visible')
})

it('Validar preenchimento obrigatório do campo Cidade', () => {
    cy.get('#logradouro').type('Rua Rosa Lima')
    cy.get('#numero').type('500')
    cy.get('#complemento').type('Casa')
    cy.get('#bairro').type('Jardim 2')
    cy.get('#estado').type('Amazonas')
    cy.get('#cep').type('58051425')
    cy.contains('Salvar').click()
    cy.contains('Preencher corretamente o campo Cidade, dúvida entrar em requisitos!').should('be.visible')
})

it('Validar quantidade mínima de caracteres no campo Cidade', () => {
    cy.get('#logradouro').type('Rua Rosa Lima')
    cy.get('#numero').type('500')
    cy.get('#complemento').type('Casa')
    cy.get('#bairro').type('Jardim 2')
    cy.get('#cidade').type('as')
    cy.get('#estado').type('Amazonas')
    cy.get('#cep').type('58051425')
    cy.contains('Salvar').click()
    cy.contains('Preencher corretamente o campo Cidade, dúvida entrar em requisitos!').should('be.visible')
})
it('Validar rejeição de números isolados no campo Cidade', () => {
    cy.get('#logradouro').type('Rua Rosa Lima')
    cy.get('#numero').type('500')
    cy.get('#complemento').type('Casa')
    cy.get('#bairro').type('Jardim 2')
    cy.get('#cidade').type('1')
    cy.get('#estado').type('Amazonas')
    cy.get('#cep').type('58051425')
    cy.contains('Salvar').click()
    cy.contains('Preencher corretamente o campo Cidade, dúvida entrar em requisitos!').should('be.visible')
})

it('Validar aceitação de apenas 2 letras no campo Estado', () => {
    cy.get('#logradouro').type('Rua Rosa Lima')
    cy.get('#numero').type('500')
    cy.get('#complemento').type('Casa')
    cy.get('#bairro').type('Jardim 2')
    cy.get('#cidade').type('Manaus')
    cy.get('#estado').type('Amazonas')
    cy.get('#cep').type('58051425')
    cy.contains('Salvar').click()
    cy.contains('Endereço cadastrado com sucesso!').should('be.visible')
})

it('Validar rejeição de UF inválida', () => {
    cy.get('#logradouro').type('Rua Rosa Lima')
    cy.get('#numero').type('500')
    cy.get('#complemento').type('Casa')
    cy.get('#bairro').type('Jardim 2')
    cy.get('#cidade').type('Manaus')
    cy.get('#estado').type('rg')
    cy.get('#cep').type('58051425')
    cy.contains('Salvar').click()
    cy.contains('UF inválida! Preencher corretamente o campo Estado, dúvida entrar em requisitos!').should('be.visible')
})
it('Validar preenchimento obrigatório do campo CEP', () => {
    cy.get('#logradouro').type('Rua Rosa Lima')
    cy.get('#numero').type('500')
    cy.get('#complemento').type('Casa')
    cy.get('#bairro').type('Jardim 2')
    cy.get('#cidade').type('Manaus')
    cy.get('#estado').type('Amazonas')
    cy.contains('Salvar').click()
    cy.contains('Preencher corretamente o campo CEP, dúvida entrar em requisitos!').should('be.visible')
})

it('Validar aceitação apenas de números no campo CEP', () => {
    cy.get('#logradouro').type('Rua Rosa Lima')
    cy.get('#numero').type('500')
    cy.get('#complemento').type('Casa')
    cy.get('#bairro').type('Jardim 2')
    cy.get('#cidade').type('Manaus')
    cy.get('#estado').type('Amazonas')
    cy.get('#cep').type('asdafasf')
    cy.contains('Salvar').click()
    cy.contains('Preencher corretamente o campo CEP, dúvida entrar em requisitos!').should('be.visible')
})

it('Validar redirecionamento para tela Home ao clicar em Voltar', () => {
    cy.contains('Voltar').click()
    cy.contains('QAPlayground | Ambiente de prática e experimentação para QAs').should('be.visible')
});

})
